FROM mcr.microsoft.com/playwright:v1.64.0-jammy@sha256:c064e7f355d2dda32f669801a1b09e86a1e9252395c844d2cfbbe5c44acb9b79

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY playwright.config.js ./
COPY global-setup.ts ./
COPY ./src/e2e-tests ./src/e2e-tests

CMD [ "npm", "run", "e2e-tests" ]


