name: Update gh-pages (latest)

env:
  DOCKER_REGISTRY: hub.terrestris.de/shogun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources 🔰
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Setup Node.js 🧮
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24

    - name: Cache Node.js modules 💾
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies ⏬
      run: npm ci

    - name: Build artifacts 🏗️
      run: npm run build

    - name: Deploy (to latest) 🚀
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
        target-folder: latest

    - name: Login to Docker Registry ⌨️
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build docker image (main) 🏗️
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        context: .
        tags: |
          ${{ env.DOCKER_REGISTRY }}/shogun-gis-client:main
        load: true

    - name: Push docker image to Docker Registry (main) 📠
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/shogun-gis-client:main

    - name: Build docker image e2e-tests (main) 🏗️
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        file: Dockerfile.e2e
        context: .
        tags: |
          ${{ env.DOCKER_REGISTRY }}/shogun-gis-client-e2e-tests:main
        load: true

    - name: Push docker image to Docker Registry (main) 📠
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/shogun-gis-client-e2e-tests:main

  sonarqube:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node.js 🧮
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Cache Node.js modules 💾
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        run: npm ci

      - name: Test code ✅
        run: npm run test
        env:
          CI: true

      - name: Get shogun-gis-client version 🔖
        run: |
          echo "sonar.projectVersion=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> ./sonar-project.properties

      - name: SonarQube Scan 🔬
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
