name: Update gh-pages (release)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources 🔰
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Setup Node.js 🧮
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 24

    - name: Cache Node.js modules 💾
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies ⏬
      run: npm ci

    - name: Build artifacts 🏗️
      run: npm run build

    - name: Get shogun-gis-client version 🔖
      run: |
        echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

    - name: Deploy (to v${{ env.VERSION }}) 🚀
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
        target-folder: v${{ env.VERSION }}
