name: Update gh-pages (release)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources 🔰
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Setup Node.js 🧮
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24

    - name: Cache Node.js modules 💾
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies ⏬
      run: npm ci

    - name: Build artifacts 🏗️
      run: npm run build

    - name: Get shogun-gis-client version 🔖
      run: |
        echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

    - name: Deploy (to v${{ env.VERSION }}) 🚀
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
        target-folder: v${{ env.VERSION }}
