name: Release Docker

on:
  workflow_call: # allows being called by other workflows
    inputs:
      release_is_published:
        required: true
        type: string
      release_version:
        required: true
        type: string
    secrets:
      docker_registry_user:
        required: true
      docker_registry_pass:
        required: true

env:
  DOCKER_REGISTRY: hub.terrestris.de/shogun

jobs:
  release-docker:
    name: Release Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: v${{ inputs.release_version }}

      - name: Login to Docker Registry ⌨️
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.docker_registry_user }}
          password: ${{ secrets.docker_registry_pass }}

      - name: Build docker image (latest)
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          tags: |
            ${{ env.DOCKER_REGISTRY }}/shogun-gis-client:latest
          load: true
          build-args: |
            APP_VERSION=latest
            GIT_COMMIT=${{ github.sha }}

      - name: Build docker image (version)
        if: ${{ inputs.release_is_published }} == 'true'
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          tags: |
            ${{ env.DOCKER_REGISTRY }}/shogun-gis-client:${{ inputs.release_version }}
          load: true
          build-args: |
            APP_VERSION=${{ inputs.release_version }}
            GIT_COMMIT=${{ github.sha }}

      - name: Push docker image to Docker registry (latest)
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/shogun-gis-client:latest

      - name: Push docker image to Docker registry (version)
        if: ${{ inputs.release_is_published }} == 'true'
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/shogun-gis-client:${{ inputs.release_version }}

      - name: Build docker image e2e-tests (latest) 🏗️
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          file: Dockerfile.e2e
          context: .
          tags: |
            ${{ env.DOCKER_REGISTRY }}/shogun-gis-client-client-e2e-tests:latest
          load: true

      - name: Build docker image e2e-tests (version) 🏗️
        if: ${{ inputs.release_is_published }} == 'true'
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          file: Dockerfile.e2e
          context: .
          tags: |
            ${{ env.DOCKER_REGISTRY }}/shogun-gis-client-client-e2e-tests:${{ inputs.release_version }}
          load: true

      - name: Push e2e-tests docker image to Docker registry (latest) 📠
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/shogun-gis-client-client-e2e-tests:latest

      - name: Push e2e-tests docker image to Docker registry (version) 📠
        if: ${{ inputs.release_is_published }} == 'true'
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/shogun-gis-client-client-e2e-tests:${{ inputs.release_version }}
